version: 2
updates:
  # Maintain Python packages
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: dev
    commit-message:
      prefix: "[Dependabot]"
    labels:
      - Dependencies
    reviewers:
      - Paebbels
    schedule:
      interval: "weekly"

  # Maintain GitHub Action runners
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: dev
    commit-message:
      prefix: "[Dependabot]"
    labels:
      - Dependencies
    reviewers:
      - Paebbels
    schedule:
      interval: "weekly"
